# Generated by Django 6.0 on 2025-12-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('place_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('bar', 'Bar'), ('popup', 'Pop-up Shop'), ('gallery', 'Art Gallery'), ('museum', 'Museum'), ('park', 'Park'), ('event_space', 'Event Space'), ('boutique', 'Boutique'), ('bookstore', 'Bookstore'), ('market', 'Market'), ('theater', 'Theater'), ('other', 'Other')], max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('aesthetic_tags', models.JSONField(blank=True, default=list)),
                ('mood_tags', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('views_count', models.IntegerField(default=0)),
                ('saves_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'place_type'], name='places_plac_city_604ec1_idx'), models.Index(fields=['is_active', '-created_at'], name='places_plac_is_acti_9925d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('concert', 'Concert'), ('exhibition', 'Exhibition'), ('workshop', 'Workshop'), ('market', 'Market'), ('popup', 'Pop-up'), ('festival', 'Festival'), ('screening', 'Screening'), ('performance', 'Performance'), ('other', 'Other')], max_length=50)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('website', models.URLField(blank=True)),
                ('ticket_url', models.URLField(blank=True)),
                ('price_info', models.CharField(blank=True, max_length=100)),
                ('aesthetic_tags', models.JSONField(blank=True, default=list)),
                ('mood_tags', models.JSONField(blank=True, default=list)),
                ('views_count', models.IntegerField(default=0)),
                ('interested_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='places.place')),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_saves', to='places.place')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
